"""Add transaction import field

Revision ID: 435547ff231a
Revises: 03574760978b
Create Date: 2026-01-07 19:07:18.497728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435547ff231a'
down_revision = '03574760978b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('merchant_state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mcc', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('use_chip', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_fraud', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('is_fraud')
        batch_op.drop_column('use_chip')
        batch_op.drop_column('mcc')
        batch_op.drop_column('merchant_zip')
        batch_op.drop_column('merchant_state')
        batch_op.drop_column('merchant_city')

    # ### end Alembic commands ###
