"""Split interests_and_motivation_enabled into separate fields

Revision ID: 5f157178c1f5
Revises: 27ecb6bf66a3
Create Date: 2026-01-24 15:26:22.580644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f157178c1f5'
down_revision = '27ecb6bf66a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add new separate toggle fields
        batch_op.add_column(sa.Column('interests_enabled', sa.Boolean(), nullable=True, server_default=sa.false()))
        batch_op.add_column(sa.Column('motivations_enabled', sa.Boolean(), nullable=True, server_default=sa.false()))
        # Drop the old combined field
        batch_op.drop_column('interests_and_motivation_enabled')
        
        batch_op.alter_column('has_completed_persona_quiz',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('FALSE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Restore the old combined field
        batch_op.add_column(sa.Column('interests_and_motivation_enabled', sa.Boolean(), nullable=True, server_default=sa.false()))
        # Drop the new separate fields
        batch_op.drop_column('motivations_enabled')
        batch_op.drop_column('interests_enabled')
        
        batch_op.alter_column('has_completed_persona_quiz',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('FALSE'))

    # ### end Alembic commands ###
