"""Add categorization confidence and source fields to Transaction

Revision ID: c8325b5cdee5
Revises: fad21fa3441b
Create Date: 2026-01-12 20:26:05.821145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8325b5cdee5'
down_revision = 'fad21fa3441b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorization_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('categorization_source', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('categorization_source')
        batch_op.drop_column('categorization_confidence')

    # ### end Alembic commands ###
