"""Add Account model and update Transaction model for new CSV format

Revision ID: fad21fa3441b
Revises: 4e7e9e77aaaa
Create Date: 2026-01-12 19:52:06.616677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad21fa3441b'
down_revision = '4e7e9e77aaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('institution', sa.String(length=100), nullable=True),
    sa.Column('card_last_4', sa.String(length=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_account_id', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_account_id', type_='foreignkey')
        batch_op.drop_column('is_recurring')
        batch_op.drop_column('merchant_country')
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('balance_after')
        batch_op.drop_column('account_id')

    op.drop_table('accounts')
    # ### end Alembic commands ###
